### ISSUE TITLE
Tic-tac-toe Game

### ISSUE THREAD

**Issue by dwijmistry11** [dwijmistry11/project-hub#14]
Tic-tac-toe, also known as nougats and crosses or Xs and Os, is a two-person paper and pencil game in which each player alternates marking squares in a three-by-three grid with an X or an O. The winner is the player who successfully places three of their markers in a horizontal, vertical, or diagonal row. You can implement this fun game using 2D arrays in the C programming language. It is important to use arrays while creating a Tic Tac Toe game in the C programming language. The Xs and Os are stored in separate arrays and passed across various functions in the code to maintain track of the game’s progress. You can play the game against the computer by entering the code here and selecting either X or O. The source code for the project is given below.

**Comment by AwsYaseen22** [comment]
Hi @dwijmistry11, Can I do this?

**Comment by dwijmistry11** [comment]
sure @AwsYaseen22

**Comment by AwsYaseen22** [comment]
is ok to do it with react?!

**Comment by dwijmistry11** [comment]
yes you can but please explain all in readme.md

**Comment by AwsYaseen22** [comment]
Great 👍
