### ISSUE TITLE
add how to submit your project? in readme.md

### ISSUE THREAD

**Issue by dwijmistry11** [dwijmistry11/project-hub#4]

**Comment by proffapt** [comment]
how exactly to submit ?

**Comment by dwijmistry11** [comment]
> how exactly to submit ?

# How to contribute?
* Star this repo
* Fork this repo
* clone forked repo in your system
* create a folder of your project without space (eg. this-is-my-project-name)
* add your project files
* create readme.md
* add details of your project in readme.md
* write requirement and steps of how to reproduce the output in readme.md
* push it on issue named branch.
* create merge request.
